services:
  Tardigrades\SectionField\Generator\EntityGenerator:
    autowire: false
    arguments:
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'
      $container: '@service_container'

  section_field.generator.entity_generator: '@Tardigrades\SectionField\Generator\EntityGenerator'
